### ISSUE TITLE
Missing anno_txt in VIL-100

### ISSUE THREAD

**Issue by SJLNNU** [Sephirex-X/ADNet#1]
Hi, Nice Work!
 It seems you have an extra annotation fold named anno_txt compare with original dataset.
![image](https://github.com/Sephirex-X/ADNet/assets/31751988/5d4dc6fb-2976-47bc-aadd-16d01bf14fc5)
Can you please provide the generation code?  Thanks

**Comment by Sephirex-X** [comment]
Here you can find anno_txt.zip 
https://drive.google.com/file/d/1SizP9p0n-x-GhHmpYNyhMPBpPQgS3enI/view?usp=drive_link
