### ISSUE TITLE
前辈，关于SPGU的疑惑

### ISSUE THREAD

**Issue by RDXiaoLu** [Sephirex-X/ADNet#11]
我使用SPGU加入到我的模型中，仅仅加入hm_loss和thea_loss（热图生成方式和您一样）。   导致iou和reg_xytl收敛不了，想问一下我这样的加入方式有什么问题吗？我的q :1505489620@qq.com，希望得到前辈的帮助！谢谢了。

**Comment by RDXiaoLu** [comment]
如果前辈看到了请给个回复，谢谢前辈如此优秀的工作！

**Comment by Sephirex-X** [comment]
> 我使用SPGU加入到我的模型中，仅仅加入hm_loss和thea_loss（热图生成方式和您一样）。 导致iou和reg_xytl收敛不了，想问一下我这样的加入方式有什么问题吗？我的q :[1505489620@qq.com](mailto:1505489620@qq.com)，希望得到前辈的帮助！谢谢了。

Hi, thank you for your interest. You can check if the SPGU module works properly in the first place. To do so, you may remove the regression loss and visualize whether the SPGU output is similar to what was shown in the paper.

**Comment by RDXiaoLu** [comment]
Thank you so much, I was about to give up, but your answer once again inspired me, I will try it.




一切不容易
***@***.***

**Comment by RDXiaoLu** [comment]
前辈您好，当我去掉了回归loss， 只保留hm loss 以及 thea loss 以及 cls_loss。 输出图片如下
![result2_epoch1](https://github.com/user-attachments/assets/ff46e556-8554-4f6a-8df1-9d827b4ba795)
然后如果hm_loss 以及 thea_loss能下降是不是就可以判断SPGU正常工作？

**Comment by RDXiaoLu** [comment]
> 前辈您好，当我去掉了回归loss， 只保留hm loss 以及 thea loss 以及 cls_loss。输出图片如下 ![result2_epoch1](https://private-user-images.githubusercontent.com/87572685/391460723-ff46e556-8554-4f6a-8df1-9d827b4ba795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjc0MDAsIm5iZiI6MTczMzEyNzEwMCwicGF0aCI6Ii84NzU3MjY4NS8zOTE0NjA3MjMtZmY0NmU1NTYtODU1NC00ZjZhLThkZjEtOWQ4MjdiNGJhNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA4MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OTkwNTE2NzNhZDBjMGU0ZGZjZDE2MDBhNGViZWFmNzRlODYwMzRkMGZjMTlkMTFlMWNhMjUwMDAzMTkxMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NPWI9RHuu9b1nAeUOCUT5a4XFDYBJlibt3saO2cVgvM) 然后，如果hm_loss 以及 thea_loss能下降是不是就可以判断SPGU正常工作？

原始图片为：
![demo](https://github.com/user-attachments/assets/94cc0075-0bea-439d-818b-37a1732883c7)

**Comment by RDXiaoLu** [comment]
谢谢前辈的答复
