### ISSUE TITLE
What is python version in this project?

### ISSUE THREAD

**Issue by tam-pham-ts** [Sephirex-X/ADNet#2]
Hi guy, can you tell me what python version you use in this project? Many thanks.

**Comment by Muzixingxi** [comment]
Excuse me, I am currently unable to obtain F1 metrics from the culane dataset in "Normal", "Crowded" and other scenarios from the test results, I would appreciate it if you could let me know

**Comment by Sephirex-X** [comment]
> Hi guy, can you tell me what python version you use in this project? Many thanks.

As far as I know, python version >= 3 is fine.
