### ISSUE TITLE
How to export onnx model?

### ISSUE THREAD

**Issue by Byronnar** [Sephirex-X/ADNet#7]
Anyone know how to export onnx model?

**Comment by Muzixingxi** [comment]
Excuse me, I am currently unable to obtain F1 metrics from the culane dataset in "Normal", "Crowded" and other scenarios from the test results, I would appreciate it if you could let me know

**Comment by Sephirex-X** [comment]
> Anyone know how to export onnx model?

Sorry, we haven’t tried exporting to an ONNX model and don’t have plans to do so.
